apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: load-balancing-simulator-ns
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: loadbalancer_simulator