apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: load-balancing-simulator-ns
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "loadbalancer_simulator"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "true"